# Copy to config.toml for local patches
[net]
git-fetch-with-cli = true

[patch."https://github.com/openvm-org/openvm.git"]
openvm-sdk = { path = "../openvm-scroll-tech/crates/sdk" }
openvm = { path = "../openvm-scroll-tech/crates/toolchain/openvm" }
openvm-build = { path = "../openvm-scroll-tech/crates/toolchain/build" }
openvm-circuit = { path = "../openvm-scroll-tech/crates/vm" }
openvm-pairing = { path = "../openvm-scroll-tech/guest-libs/pairing" }
openvm-algebra-guest = { path = "../openvm-scroll-tech/extensions/algebra/guest" }
openvm-ecc-guest = { path = "../openvm-scroll-tech/extensions/ecc/guest" }

[patch."https://github.com/scroll-tech/openvm.git"]
openvm-benchmarks-prove = { path = "../openvm-scroll-tech/benchmarks/prove" }
# OpenVM
openvm-sdk = { path = "../openvm-scroll-tech/crates/sdk" }
cargo-openvm = { path = "../openvm-scroll-tech/crates/cli" }
openvm-mod-circuit-builder = { path = "../openvm-scroll-tech/crates/circuits/mod-builder" }
openvm-poseidon2-air = { path = "../openvm-scroll-tech/crates/circuits/poseidon2-air" }
openvm-circuit-primitives = { path = "../openvm-scroll-tech/crates/circuits/primitives" }
openvm-circuit-primitives-derive = { path = "../openvm-scroll-tech/crates/circuits/primitives/derive" }
openvm = { path = "../openvm-scroll-tech/crates/toolchain/openvm" }
openvm-build = { path = "../openvm-scroll-tech/crates/toolchain/build" }
openvm-instructions = { path = "../openvm-scroll-tech/crates/toolchain/instructions" }
openvm-instructions-derive = { path = "../openvm-scroll-tech/crates/toolchain/instructions/derive" }
openvm-macros-common = { path = "../openvm-scroll-tech/crates/toolchain/macros" }
openvm-platform = { path = "../openvm-scroll-tech/crates/toolchain/platform" }
openvm-transpiler = { path = "../openvm-scroll-tech/crates/toolchain/transpiler" }
openvm-circuit = { path = "../openvm-scroll-tech/crates/vm" }
openvm-circuit-derive = { path = "../openvm-scroll-tech/crates/vm/derive" }

# Extensions
openvm-algebra-circuit = { path = "../openvm-scroll-tech/extensions/algebra/circuit" }
openvm-algebra-transpiler = { path = "../openvm-scroll-tech/extensions/algebra/transpiler" }
openvm-algebra-guest = { path = "../openvm-scroll-tech/extensions/algebra/guest" }
openvm-algebra-moduli-macros = { path = "../openvm-scroll-tech/extensions/algebra/moduli-macros" }
openvm-algebra-complex-macros = { path = "../openvm-scroll-tech/extensions/algebra/complex-macros" }
openvm-bigint-circuit = { path = "../openvm-scroll-tech/extensions/bigint/circuit" }
openvm-bigint-transpiler = { path = "../openvm-scroll-tech/extensions/bigint/transpiler" }
openvm-bigint-guest = { path = "../openvm-scroll-tech/extensions/bigint/guest" }
openvm-ecc-circuit = { path = "../openvm-scroll-tech/extensions/ecc/circuit" }
openvm-ecc-transpiler = { path = "../openvm-scroll-tech/extensions/ecc/transpiler" }
openvm-ecc-guest = { path = "../openvm-scroll-tech/extensions/ecc/guest" }
openvm-ecc-sw-macros = { path = "../openvm-scroll-tech/extensions/ecc/sw-macros" }
openvm-keccak256-circuit = { path = "../openvm-scroll-tech/extensions/keccak256/circuit" }
openvm-keccak256-transpiler = { path = "../openvm-scroll-tech/extensions/keccak256/transpiler" }
openvm-keccak256-guest = { path = "../openvm-scroll-tech/extensions/keccak256/guest" }
openvm-sha256-circuit = { path = "../openvm-scroll-tech/extensions/sha256/circuit" }
openvm-sha256-transpiler = { path = "../openvm-scroll-tech/extensions/sha256/transpiler" }
openvm-sha256-guest = { path = "../openvm-scroll-tech/extensions/sha256/guest" }
openvm-native-circuit = { path = "../openvm-scroll-tech/extensions/native/circuit" }
openvm-native-compiler = { path = "../openvm-scroll-tech/extensions/native/compiler" }
openvm-native-compiler-derive = { path = "../openvm-scroll-tech/extensions/native/compiler/derive" }
openvm-native-recursion = { path = "../openvm-scroll-tech/extensions/native/recursion" }
openvm-pairing-circuit = { path = "../openvm-scroll-tech/extensions/pairing/circuit" }
openvm-pairing-transpiler = { path = "../openvm-scroll-tech/extensions/pairing/transpiler" }
openvm-pairing-guest = { path = "../openvm-scroll-tech/extensions/pairing/guest" }
openvm-rv32-adapters = { path = "../openvm-scroll-tech/extensions/rv32-adapters" }
openvm-rv32im-circuit = { path = "../openvm-scroll-tech/extensions/rv32im/circuit" }
openvm-rv32im-transpiler = { path = "../openvm-scroll-tech/extensions/rv32im/transpiler" }
openvm-rv32im-guest = { path = "../openvm-scroll-tech/extensions/rv32im/guest" }

# Guest Libs
k256 = { path = "../openvm-scroll-tech/guest-libs/k256" }
p256 = { path = "../openvm-scroll-tech/guest-libs/p256" }
openvm-keccak256 = { path = "../openvm-scroll-tech/guest-libs/keccak256" }
openvm-sha2 = { path = "../openvm-scroll-tech/guest-libs/sha2" }
openvm-pairing = { path = "../openvm-scroll-tech/guest-libs/pairing" }

# NOTE: do not patch k256 for host as it causes some issues
# [patch.crates-io]
# k256 = { path = "../openvm-scroll-tech/guest-libs/k256" }
# p256 = { path = "../openvm-scroll-tech/guest-libs/p256" }
# revm = { path = "../revm/crates/revm" }
# revm-primitives = { path = "../revm/crates/primitives" }
# revm-interpreter = { path = "../revm/crates/interpreter" }
# revm-precompile = { path = "../revm/crates/precompile" }

[patch."https://github.com/openvm-org/stark-backend.git"]
openvm-stark-sdk = { path = "../stark-backend/crates/stark-sdk" }
openvm-cuda-backend = { path = "../stark-backend/crates/cuda-backend" }
openvm-cuda-common = { path = "../stark-backend/crates/cuda-common" }
openvm-stark-backend = { path = "../stark-backend/crates/stark-backend" }

[patch."https://github.com/scroll-tech/ceno.git"]
ceno_rt = { path = "../ceno/ceno_rt" }
ceno_crypto = { path = "../ceno/guest_libs/crypto" }
ceno_emul = { path = "../ceno/ceno_emul" }
ceno_host = { path = "../ceno/ceno_host" }
ceno_zkvm = { path = "../ceno/ceno_zkvm" }
ceno_sha2 = { path = "../ceno/guest_libs/sha2" }
ceno_cli = { path = "../ceno/ceno_cli", package = "cargo-ceno" }
ceno_recursion = { path = "../ceno/ceno_recursion" }
