[bans]
multiple-versions = "deny"

skip = [
    { name = "ark-ff" },
    { name = "ark-ff-asm" },
    { name = "ark-ff-macros" },
    { name = "ark-serialize" },
    { name = "ark-std" },
    { name = "bincode" },
    { name = "cargo-platform" },
    { name = "cargo_metadata" },
    { name = "darling" },
    { name = "darling_core" },
    { name = "darling_macro" },
    { name = "derive-new" },
    { name = "derive_more" },
    { name = "derive_more-impl" },
    { name = "ecdsa" },
    { name = "ff" },
    { name = "foldhash" },
    { name = "generic-array" },
    { name = "getrandom" },
    { name = "group" },
    { name = "hashbrown" },
    { name = "itertools" },
    { name = "k256" },
    { name = "lru" },
    { name = "num-bigint" },
    { name = "num-modular" },
    { name = "num_enum" },
    { name = "num_enum_derive" },
    { name = "ordered-float" },
    { name = "pairing" },
    { name = "pasta_curves" },
    { name = "proc-macro-crate" },
    { name = "rfc6979" },
    { name = "serde_spanned" },
    { name = "strum" },
    { name = "strum_macros" },
    { name = "syn" },
    { name = "thiserror" },
    { name = "thiserror-impl" },
    { name = "toml" },
    { name = "toml_datetime" },
    { name = "toml_edit" },
    { name = "unicode-width" },
    { name = "windows-sys" },
    { name = "windows-targets" },
    { name = "windows_aarch64_gnullvm" },
    { name = "windows_aarch64_msvc" },
    { name = "windows_i686_gnu" },
    { name = "windows_i686_gnullvm" },
    { name = "windows_i686_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_x86_64_gnullvm" },
    { name = "windows_x86_64_msvc" },
    { name = "winnow" },
]
