name: "PR"

on:
  push:
    branches:
      - "main"
  # Disable for now
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  lock-files:
    name: "Check lock files"
    runs-on: [self-hosted, x64, linux, gpu]
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SECRET_FOR_CENO_GPU }}
      - name: "Checkout sources"
        uses: "actions/checkout@v4"

      - name: "Update lock files"
        run: |
          cargo tree
          (cd ./bin/client-eth && cargo tree)

      - name: "Assert no changes"
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Lock files not up to date"
            exit 1
          fi

  fmt:
    name: "Check code format"
    runs-on: [self-hosted, x64, linux, gpu]
    steps:
      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SECRET_FOR_CENO_GPU }}
      - name: "Checkout sources"
        uses: "actions/checkout@v4"

      - name: "Setup nightly toolchain"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "nightly"
          profile: "minimal"
          components: "rustfmt"
          override: true

      - name: "Check Rust format"
        run: |
          cargo fmt --all -- --check
